### ISSUE TITLE
Streamlit integration (local)

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#107]
## 🚀 Feature
We need a quick demo on how to use streamlit with mantisshrimp. The first step in to get it running locally.

We should also add helpers functions to make the process easier.

**Comment by paras-jain** [comment]
I'm running late because of STOC, will push code asap.

**Comment by lgvaz** [comment]
Don't worry!

I created the issue just to make it more organized

**Comment by oke-aditya** [comment]
Should help #99 and #83 

Something to get strated
https://github.com/streamlit/demo-self-driving

**Comment by oke-aditya** [comment]
Minimalistic (non-inference code) is working fine locally. We need to add model and run it. Repo is [here]( https://github.com/oke-aditya/mantisshrimp_streamlit).

You can simply give me a s3 bucket link/dropbox file link. I have made a progress bar loader too for download.

**Comment by lgvaz** [comment]
I'll try this tomorrow!!

**Comment by ai-fast-track** [comment]
Let's try to use Google Drive as a first attempt and take it from there: The notebooks + datasets will be hosted at the same place avoiding to deal with 2 separate providers.

**Comment by lgvaz** [comment]
I'm thinking the datasets are not going to be hosted by us, instead we should use the original source whenever posssible

**Comment by ai-fast-track** [comment]
Agree! I actually referring more the the weights files.

**Comment by oke-aditya** [comment]
Almost there with [this ](https://github.com/oke-aditya/mantisshrimp_streamlit) repo. We just need to use the predict function of mantisshrimp. And it should display the results to the user. The other NMS and searching via the class needs a bit of work. Please try to run this repo and let me know the changes. 

You can even raise a PR if something is not working or you have an improvement and update.

**Comment by lgvaz** [comment]
I ran it yesterday and it worked perfectly (apart from what we already discussed) 😄

Please let us know again when you add prediction. For now, don't bother trying to fix the deployment issues, let's first get this going locally and then we figure out

**Comment by oke-aditya** [comment]
- I fixed that small thing. Prediction will be done hopefully this week. Then we can see about the sidebar thingie of how much customization we can give to user.

**Comment by oke-aditya** [comment]
Almost done. A bit of final touch ups are left. I guess we can add this demo to read me too.

**Comment by oke-aditya** [comment]
Can you guys please test [this](https://github.com/oke-aditya/mantisshrimp_streamlit) repo?
```
pip install -r requirements.txt
streamlit run src/object_detection_app.py
```

**Comment by lgvaz** [comment]
It works!

![image](https://user-images.githubusercontent.com/16520544/87106632-47634f00-c234-11ea-96af-48e8194e1eac.png)

Prediction is wrong, but I think that's caused by the low image resolution

**Comment by ai-fast-track** [comment]
It works!

**Comment by oke-aditya** [comment]
Great. Please provide me some images from Pets dataset itself so that we can show it works well.
I will polish up the app once more and then we can close this issue..

**Comment by paras-jain** [comment]
Works well!🎉
Have sent you some images from pets.

**Comment by lgvaz** [comment]
> Please provide me some images from Pets dataset itself so that we can show it works well.

It's a better idea just to google some images, I used a random seed and I don't know what was in train/valid

**Comment by oke-aditya** [comment]
Yep, Pras helped me to fix it up. Now the predictions look better. We can improve the app further and refine for the sidebar UX. But I will leave this as scope for future improvement for now. 
I am updating the readme to have link to [this](https://github.com/oke-aditya/mantisshrimp_streamlit) repo. We can close the issue with this.

**Comment by oke-aditya** [comment]
I Guess we can close this.
