### ISSUE TITLE
Load pretrained model heads

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#110]
## 🐛 Bug
**Describe the bug**
Currently there is not way of getting a model (FasterRCNN/MaskRCNN) with a pretrained head.

Even if we used the default argument `backbone=None` the head get's replaced.

How can we transparently give back the pretrained head on coco?

Options:
* Have an extra argument (I don't like this approach because this argument would only make sense when `backbone=None` and we `num_classes=91`, additionally, if the user wants to use another dataset that is not coco, a pretrained head does not make any sense at all)  
*  `classmethod` `from_coco_pretrained`, something like that?

**Comment by lgvaz** [comment]
Currently we can load the weights like so:
```python
model = MantisMaskRCNN(91)
state_dict = hub.load_state_dict_from_url(
    'https://download.pytorch.org/models/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth',
    progress=True)
model.model.load_state_dict(state_dict)
```

**Comment by lgvaz** [comment]
I quite like this approach for loading the weights, it's very intuitive for anyone using pytorch, the only thing that bothers me is `model.model`

**Comment by oke-aditya** [comment]
This is good why not make it standard API for all models. Maybe tomorrow user trains on KITTI dataset and wants to just load in the weights. 

Have a load_state_dict withing the parent model class itself. so that user can directly do ```model.load_state_dict()```

**Comment by lgvaz** [comment]
An issue is that we cannot have that in the base class, if you take a look at `MantisRCNN` it doesn't have any idea about `model`

What we can do is add `load_state_dict` as an abstract method the inheritors have to implement

**Comment by oke-aditya** [comment]
People will not like to implement this. As it is very core torch native stuff.

We should have something like 
`model = WheatModel()`
`model.load_state_dict("path_to_pt")`
