### ISSUE TITLE
Add colab version to all tutorials

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#123]
All tutorials need to be available on colab.

Not a hard task, just need to install the dependencies at the beginning of the notebook and add the colab badge. 

- [x] introduction guide
- [ ] custom parsers
- [ ] custom backbones
- [ ] pluggable mantisshrimp (outdated link)

**Comment by paras-jain** [comment]
Wheat and mantisshrimp-fasterrcnn is done, working on others. Will submit a PR for all at once. Please add pets too, its colab version is also ready.

**Comment by lgvaz** [comment]
Nice!! You just need to work on the ones that show on the documentation, the others are probably going to be refactored or removed.

I'll update the list in the OP

**Comment by paras-jain** [comment]
Yes that is what I was thinking, thanks for clarifying. 😃

**Comment by lgvaz** [comment]
The tutorials described here are outdated, we can open a new issue for this if necessary
