### ISSUE TITLE
Clean tutorials

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#124]
We have a good variety of tutorials, but some of them have a lot of duplication, and there is not a clear order on how they should be read.

The first task is to rename the tutorials, we need to number them and improve the names.

For example, `wheat.py` should become `1 - Quickstart`

Maybe some of the tutorials should even be deleted for sake of clarity.

It's also worth saying that not all tutorials need to show on the documentation. We select what tutorials we want to show in `docs/source/tutorials`

**Comment by oke-aditya** [comment]
Wheat.py is already made Quickstart 😄  I made this edit last time I pushed advanced tutorial.

Let's list out what to include in Beginner's docs and then what in advanced docs.

**Comment by lgvaz** [comment]
> Wheat.py is already made Quickstart

I mean the name of the file itself as well =)

**Comment by oke-aditya** [comment]
Quick link to acces it with the issue. https://lgvaz.github.io/mantisshrimp/index.html

I will rename the tutorials.

Section Mantisshrimp Models

1. Quickstart FasterRCNN.
2. Advanced FasterRCNN

Section Mantisshrimp Hub
1. Detr Fine-Tuning

Section Undertstanding Mantisshrimp Data
1. Quickstart Parsers.

**Comment by ai-fast-track** [comment]
A lot better!. Maybe the Data section should go before the Hub section

**Comment by oke-aditya** [comment]
Will do that.
