### ISSUE TITLE
Rescale transforms and torchvision RCNNs

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#131]
## 🐛 Bug
torchvisions `FasterRCNN` and `MaskRCNN` internally rescales the images via `GeneralizedRCNNTransform`.

This means that any resizing transform previously applied to the image (probably on the `Dataset` stage) will be unexpectedly  overriden.

It becomes really confusing if we should apply a resize transform via `Dataset` or via the model, ideally we want all transform to be applied at the `Dataset` stage. Going one step further, can this even be said about normalization?

## Solution 1
Changes the default of `min_size` and `max_size` in the model to 2 and 9999 respectively, practically making them non effective.

## Solution 2
Monkey patch `model.transform` to a function that returns the same items it receives (being careful with what are the expected output types)

---
Solution 1 seems like a better idea, it's less magical, we can still have `min/max_size` as parameters, we just change their defaults.

---
Should we do the same with normalize? Changing the mean to 0 and std to 1? It's them clear that if we want to normalize we should do it in the `Dataset` stage.

I'm thinking this because models that we integrate in the future might not have this internal transforms, and it will be very confusing to a new user why sometimes he has to explicity define normalization and sometimes not.

**Comment by lgvaz** [comment]
@oke-aditya any thoughts?

**Comment by oke-aditya** [comment]
Generalized RCNN transform allows user to pass an image of arbitrary size and RCNN takes care of scaling etc. 

But if the user is very specific with his training size images then he may pass images of specific dimension too. And it will work fine.

Yes, future models may not have internal transforms that we think have as of now. So I guess we need to be clear with this issue. I am still unsure of solution.
