### ISSUE TITLE
Renames parsed fields to plural on tutorials.

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#146]
#128 just landed, and a now parsed fields that return lists are named in plural e.g. `bbox` -> `bboxes`.

We need to find the uses on the tutorials and rename them.

- [x] FasterRCNN Quickstart
- [ ] FasterRCNN Advanced Tutorial
- [ ] Intro to mantisshrimp parsers
- [ ] voc parser with fasterrcnn
- [ ] fine tune detr on pennfundan
- [ ] fine tune detr on wheat

**Comment by oke-aditya** [comment]
Is this fixed? I guess we have revamped tutorials so unsure of this

**Comment by lgvaz** [comment]
It's! good catch
