### ISSUE TITLE
show category name instead of id in show_*

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#148]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
It would be nice to see the category names instead of numbers.

**Describe the solution you'd like**
Pass the categories to show_* and get the numbers replaced by names.

**Comment by oke-aditya** [comment]
This is fixed right ? We are able to now get the category names on the image instead of ID.

**Comment by lgvaz** [comment]
Good catch! I forgot to link the PR, thanks!
