### ISSUE TITLE
Add efficientdet support

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#149]
## 🚀 Feature
Let's start working on adding support for efficientdet, specifically, let's work on [this](https://github.com/rwightman/efficientdet-pytorch) implementation.

A good starting point is [this](https://www.kaggle.com/shonenkov/training-efficientdet) kaggle kernel, which is using efficient det to finetune in the wheat dataset.

---
Related to #137

**Comment by oke-aditya** [comment]
Absolutely 👍

**Comment by oke-aditya** [comment]
Great. I just started looking into the ross models. Some points I want to point out before we start.
The implemenation as shown [EfficientDet](https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/efficientdet.py)
```
self.backbone = create_model(
            config.backbone_name, features_only=True, out_indices=(2, 3, 4),
            pretrained=pretrained_backbone, **config.backbone_args)
```
Makes it very very simple to use different backbones. Right from `timm` Which is ross models.

One more point.

```
The EfficientNet implementation in the effdet library takes bboxes in yxyx format. They do this in the library because the original implementation(TF version) uses yxyx format as input and decided to port it exactly. 
```

- How are we going to integrate this? Git sub-module or we patch the folders?
- We actually need only [EfficientDet](https://github.com/rwightman/efficientdet-pytorch/blob/master/effdet/efficientdet.py) file.
- Rest code we need to rewrite adapt from his repo.
- What we need to do is add adapters for lightning and fastai.
- Integrate them properly with consistent API and add preprocessing helpers.

**Comment by lgvaz** [comment]
I just opened an [issue](https://github.com/rwightman/efficientdet-pytorch/issues/50) asking general questions 😁

The extract about `yxyx` format is golden information, I was actually thinking we has using `xyxy`, where did you find that?

> How are we going to integrate this? Git sub-module or we patch the folders?
Probably `pip install` his library, no code needs to be rewritten

**Comment by lgvaz** [comment]
For the bounding boxes, inside `/data/dataset.py` we have:
```
            if self.yxyx:
                #bbox = [y1, x1, y1 + h - 1, x1 + w - 1]
                bbox = [y1, x1, y1 + h, x1 + w]
            else:
                #bbox = [x1, y1, x1 + w - 1, y1 + h - 1]
                bbox = [x1, y1, x1 + w, y1 + h]
```
And in the `__init__.py`:
```python
        self.yxyx = True   # expected for TF model, most PT are xyxy
```
It's hardcoded to true, but the comment leaves the impression that `xyxy` is used for pytorch models

**Comment by lgvaz** [comment]
Something very important that I initially missed, because this is a SSD model, we cannot feed images of different sizes in the same batch, but we need instead to normally collate the images in a single tensor of shape (bs, c, w, h)

So, the dataloader collate_fn for this one is not the same as for the rcnns

**Comment by oke-aditya** [comment]
- Yes this does not use the Generalized RCNN Transform which allows any size image to be passed. 
- It is not because it is a one-stage detector. Retina Net coming soon in PyTorch will support all these stuff despite being single stage detector.
- Solution for this: -
1. Resize the images to the user given dimensions in data loader itself.
OR
1. Ask the user to give images of consistent size.

**Comment by lgvaz** [comment]
Correct!!

The better approach is to ask to user to already gives images of a consistent size, this should happen in the `transforms` stage, when creating a `Dataset`.

**Comment by oke-aditya** [comment]
Yes, 2nd is much better Approach. Which is quite standard practice in CNNs or Object detection. Better train on Fixed size data. Which user should specify no hardcoding from our side.
