### ISSUE TITLE
batch tfms

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#159]
## 🚀 Feature

Batch transforms can help us finding the biggest image on the batch so we can pad the others and maintain the aspect ratio. Some newer transforms like CutMix also need a batch transform formulation.

Batch tfms can help inside the dataloader `collate_fn`, so they can be distributed between multiple processes, as an high level overview, we would have something like this:

```python

def custom_collate(build_batch, batch_tfms):
    def collate_fn(records: List[RecordType]):
        # batch_tfms enable us to apply batch dependent transforms
        # like cutmix or mixup, or even help with transforms to pad images
        # to a common size based on the biggest image on the batch
        # but do **not** help with GPU transforms
        # pytorch docs actually advices **against** returning GPU tensors
        # from the dataloader
        records = batch_tfms(records)
        # build batch is dependent to the model, you can image this as
        # the adapter between records and what the model expects as it input
        # it's in this phase where we convert everything into a tensor
        # and arrange the input format the model expects
        batch = build_batch(records)
        return batch

    return collate_fn
```

Each model would bring its own `build_batch`, since this is the function that serves as an adpater between the library standard `records` and what the models expect as input:
```python
train_collate_fn = custom_collate(build_batch=efficient_det.build_train_batch)
train_dl = DataLoader(train_ds, collate_fn=train_collate_fn)
```

Each model can also pack it's own `build_valid_batch` and `build_inference_batch`.

These functions don't need to be explicitly given to the user, we can instead wrap then in a higher level API that would facilitate the usage, something like so:
```python
train_dl = faster_rcnn.train_dataloader(train_ds) #collate_fn is done internally
```

**Comment by lgvaz** [comment]
To the last point, it would work like this behind the scenes:

```
def build_train_batch():
    # Specific to the model
    pass


def train_dataloader(dataset, batch_tfms=None, **kwargs):
    collate_fn = transform_collate(build_batch=build_train_batch, batch_tfms=batch_tfms)
    return DataLoader(dataset, collate_fn=collate_fn, **kwargs)
```

**Comment by lgvaz** [comment]
We can have something like this:
```python
train_dl = DataLoader(train_ds, collate_fn=efficient_det.build_train_batch(batch_tfms))
valid_dl = DataLoader(train_ds, collate_fn=efficient_det.build_valid_batch(batch_tfms))
```

And we make standard that every model has the `build_batch` function

**Comment by lgvaz** [comment]
Another option would be to have a wrapping function:
```python
train_dl = efficient_det.train_dataloader(DataLoader(train_ds), batch_tfms=batch_tfms)
valid_dl = efficient_det.valid_dataloader(DataLoader(valid_ds), batch_tfms=batch_tfms)
```

**Comment by ai-fast-track** [comment]
I'm looking into it.  I will get back to you ASAP.

**Comment by ai-fast-track** [comment]
I like the idea that the user will have to just write this:

`train_dl = faster_rcnn.train_dataloader(train_ds) #collate_fn is done internally`

And for example, the FasterRCNN class will take care of the rest, under the hood (IIUC):

```
class MantisFasterRCNN(MantisRCNN):
    ....
    
    def build_train_batch():
        # Specific to the model
        pass

    def train_dataloader(dataset, batch_tfms=None, **kwargs):
        collate_fn = transform_collate(build_batch=build_train_batch, batch_tfms=batch_tfms)
        return DataLoader(dataset, collate_fn=collate_fn, **kwargs)
```

**Comment by lgvaz** [comment]
The problem is the `**kwargs`, we should not use then, instead we have to repeat all arguments from the dataloader, and that is what bothers me

**Comment by ai-fast-track** [comment]
It's hidden, you will get used to it! haha!

On a serious note, I prefer that as opposed to having more elaborate code.
