### ISSUE TITLE
Stop importing everything everywhere 

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#181]
## 🚀 Feature

Ease of Programming vs Deployment is here.
Using from `mantisshrimp.imports import *` this causes deployment issue. It would lead to the import of unnecessary libraries and immediately give errors.

E.g. when the user needs only inference, he starts importing the model. We have `mantisshrimp.imports import *` which will try importing fastai and lightning. Which will throw an error.

Same thing for utils `mantisshrimp.utils import *`.

This is a painful refactor but this causes the biggest issue while deploying. It would be hard to program with this but if we can limit the imports it will be easy and consume less memory footprint too. We cannot create PyPI packages.
```
pip install mantisshrimp # This is not bare for ease of new users. It downloads all
pip install mantisshrimp[bare]
pip install mantisshrimp[lightning]
pip install mantisshrimp[fatai]
```

**Comment by lgvaz** [comment]
This is not happening anymore, soft dependencies are already in play

Closing this =)
