### ISSUE TITLE
Automatically log hyperparameters

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#19]
This can probably be done automatically by pytorch-lightning. More info [here](https://pytorch-lightning.readthedocs.io/en/stable/hyperparameters.html?highlight=hparams)

**Comment by lgvaz** [comment]
It seems lightning is removing hparams? [Link](https://github.com/PyTorchLightning/pytorch-lightning/pull/1896)

It's a good idea to wait on this and see what happens

**Comment by williamFalcon** [comment]
we already log hyperparameters... check the hparams tab in tensorboard

**Comment by lgvaz** [comment]
> This PR drops the hparams keyword and instead automatically logs anything passed to init

Awesome!! I was never a fan of hparams, this PR is making me very happy hahaha
