### ISSUE TITLE
Error: Inconsistent number of annotations

### ISSUE THREAD

**Issue by shimsan** [lgvaz/mantisshrimp#190]
Hi,

I am getting this error while trying out the custom_parser tutorial on my own dataset.

```
imageid->0 has an inconsistent number of annotations, all annotations must have the same length.
Number of annotations: {'labels': 16, 'bboxes': 1}
```

What does number of annotations mean?

I have converted my dataset from COCO JSON format to WheatParser CSV format.

Only change made is I added a label column, and modified WheatParser class like so:
```
    def labels(self, o) -> List[str]:
        return o.label
```

Please help me in understanding how to resolve this error.

Thanks!

**Comment by lgvaz** [comment]
The error means that for the same image, your parser is returning 16 labels but only 1 bounding box.

Probably there are some bounding boxes on your image that you're missing to parse.

**Comment by lgvaz** [comment]
Also, keep in mind that `labels` should return a list of ints, from the code provided it seems you're returning a `str`.

That is most likely the error, consider creating a dictionary that maps your strings to ints (starting from 1)

**Comment by shimsan** [comment]
Thanks! 

I changed my labels to ints, but from my JSON file my categories actually map beginning from 0. The id:0 belongs to a class that equates to 'Background', no objects to detect, no bboxes.

Right now, this is the error I see:

```
----> 3 train_records, valid_records = parser.parse(data_splitter)

2 frames
/usr/local/lib/python3.6/dist-packages/mantisshrimp/parsers/parser.py in parse(self, data_splitter, idmap, show_pbar)
     72     ) -> List[List[RecordType]]:
     73         data_splitter = data_splitter or SingleSplitSplitter()
---> 74         records = self.parse_dicted(show_pbar=show_pbar, idmap=idmap)
     75         splits = data_splitter(records.keys())
     76         return [[{"imageid": id, **records[id]} for id in ids] for ids in splits]

/usr/local/lib/python3.6/dist-packages/mantisshrimp/parsers/parser.py in parse_dicted(self, show_pbar, idmap)
     45 
     46             for name, func in annotation_parse_funcs.items():
---> 47                 records[imageid][name].extend(func(sample))
     48 
     49         # check that all annotations have the same length

<ipython-input-105-26615e917f45> in bboxes(self, o)
     27 
     28     def bboxes(self, o) -> List[BBox]:
---> 29         return [BBox.from_xywh(*np.fromstring(o.bbox[1:-1], sep=","))]

TypeError: a bytes-like object is required, not 'list'
```

I suppose we can avoid this by just using the parser for COCO you just put out. Colab is not pulling the changes yet, it says datasets.coco has no attribute 'parser'

**Comment by lgvaz** [comment]
I believe the error you're seeing comes from `np.fromstring`, is `o.bbox` a string or a list?

You said you parsed your data to a dataframe right? So the your bounding box is mostly likely already a list, if so, you can simply do `BBox.from_xywh(*o.bbox)` (assuming your bbox cordinates are "x, y, width, height".

---
For the colab error, you can either try `reset factory runtime` or install mantis again with `--upgrade` flag at the end

**Comment by shimsan** [comment]
> I believe the error you're seeing comes from `np.fromstring`, is `o.bbox` a string or a list?
> 
> You said you parsed your data to a dataframe right? So the your bounding box is mostly likely already a list, if so, you can simply do `BBox.from_xywh(*o.bbox)` (assuming your bbox cordinates are "x, y, width, height".
> 
> For the colab error, you can either try `Runtime -> reset factory runtime` or install mantis again with `--upgrade` flag at the end

Hey, thanks. Yes, I just tried converting my bbox to a string, so that it matches the expectations of the code.

I changed now to what you suggested and it works!

Only thing is how do I get the string_label to display instead of the id?

Thanks!

**Comment by lgvaz** [comment]
> Only thing is how do I get the string_label to display instead of the id?

When calling the show methods, you use the parameter `classes` to pass a list of your classes. Internally we convert the ID to the class name by indexing that list.

So if the id is 1, and your classes are ['background', 'dog'] it will show dog
