### ISSUE TITLE
Inference API

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#193]
The real hard task here is how to create a clean api that is generic and not magical behind the scenes

## Step 1 - Create a Dataset
The images can have very different sources. We may already have records that were previously parsed, or the images might be in all in a folder, or the images might be all in memory as `np.array`

I think we can safely generalize all into two sources:
* Already parsed records
* Images in memory

For all other cases, you just need to get your images in memory. If they're in a folder, you open them, if they are urls, you download them. We don't want to provide functions for all these use cases, we let the user handle how to get the images in memory

After that, from both use cases you can create a Dataset and apply some transforms if needed. For a list of images in memory we can introduce a classmethod `Dataset.from_images`

Following this, all use cases boils down to `Dataset` , so we just need to think of a single solution for that.

### Proposal 1
Until now, I've been introducing a single method for prediction that works like so:

```python
batch = efficientdet.build_infer_batch(infer_ds)
preds = efficientdet.predict(model=model, batch=batch)
```

`build_infer_batch` takes the items from the `Dataset` and converts them into the format the model expects (and this is specific to each model). `preds` is a dictionary that looks similar for all models, e.g. if a model outputs bounding boxes, it will contain a key `bboxes` that will contain a list of `BBox` objects.

You may also want to predict in batches instead of everything at once, for that you can use a `DataLoader` like so:
```python
infer_dl = efficientdet.infer_dataloader(dataset=infer_ds, batch_size=4)

all_preds = []
for batch in infer_dl:
    preds = efficientdet.predict(model=model, batch=batch)
    all_preds.extend(preds)
```

While this is a bit verbose to write, it's also very simple and straight forward, I've been advocating against a method like `predict_dl` because that might confuse the user to when use one or another, but if we decide to go for it, it would look like so:

```python
infer_dl = efficientdet.infer_dataloader(dataset=infer_ds, batch_size=4)
preds = efficientdet.predict_dl(model=model, dl=infer_dl)
```

### Proposal 2
We can reduce boilerplate a little by internally calling `build_infer_batch` in `predict` and internally calling `infer_dataloader` in `predict_dl`:

```python
preds = efficientdet.predict(model=model, dataset=infer_ds)
preds = efficientdet.predict_dl(model=model, dataset=infer_ds, batch_size=4)
```

### Proposal 3
It can be argued (although I'm not sure) that the prediction using a `DataLoader` is generic enough to handle all use cases. In that sense, we could provide a single `predict` method that internally creates a dataloader:

```python
def predict(model, dataset, batch_tfms=None, **dataloader_kwargs):
    ...
```

## The challenging problem

I believe these proposals cover the task of generating predictions reasonably well. Let's say now we want to show our predictions, somehow we need to get the images out of the dataset that was used by the model, so we need to do the following:

```python
images = [sample['img'] for sample in infer_ds]
```

And then we can simply call `show_preds`:

```python
show_preds(images, preds)
```

The problem is that this approach would fail if you're using random transforms in the dataset (I know it's uncommon to use random transforms in inference, but that should not be a limitation), because each time you index the dataset you re-apply the transforms.

I tried playing with the idea of also returning the images on predict:
```
images, preds =  efficientdet.predict(model=model, dataset=infer_ds)
```

But that introduced another set of challenges and "magic" behind the scenes.

Another thing to keep in mind is that if you resized your images, all the preds will be related to that resized image, you would need to manually rescale the predictions to match your original image.

* Can we somehow return preds related to the original images?
* How can we link the transformed images to the predictions, in a way we don't need to reindex the `Dataset`?

**Comment by lgvaz** [comment]
While refactoring the introduction_guide I had some clarity.

The combo `build_infer_batch` + `predict` is generic enough to handle any use case, and it's super easy to add a `DataLoader` into the mix:

```python
dl = DataLoader(valid_ds, batch_size=8, collate_fn=lambda o: o)

for samples in dl:
    batch = faster_rcnn.build_infer_batch(samples)
    preds = faster_rcnn.predict(model=model, batch=batch, detection_threshold=.8)
```

The `DataLoader` uses a `collate_fn` that returns what it receives, this means it can be used for any model! Cool thing is that you can use anything in there, a list of images, a dataset, a list of records, a list of filepaths, anything! You then take care of business inside the for loop.

---
I'm still thinking if we can safely combine `build_infer_batch` + `predict`

And still unclear about the "challenging problem"

**Comment by ai-fast-track** [comment]
Why not replacing  `collate_fn=lambda o: o`   by `collate_fn=im2tensor_collate` : I'm just throwing a temporary name to keep track.

The `im2tensor_collate` will have the task to apply i`m2tensor` for each image. This task is currently handled by the `build_infer_batch` method. By using `im2tensor_collate`  we could get rid of this line of code:
`batch = faster_rcnn.build_infer_batch(samples)`

The final code will be something like this:

```
for batch in dl:
    preds = faster_rcnn.predict(model=model, batch=batch, detection_threshold=.8)
```

**Comment by lgvaz** [comment]
> Why not replacing collate_fn=lambda o: o by collate_fn=im2tensor_collate

We cannot do that because the `im2tensor_collate` will not work for every model. For example, it would work for faster_rcnn because it only requires images as inputs, but it would fail for efficientdet, which requires 3 inputs: images, img_scales, img_sizes

So this means that we would need a specific collate_fn for each model, which is the same as saying we need a specific dataloader for each model, hence the original solution with `infer_dataloader`

**Comment by lgvaz** [comment]
Actually... You could do:

```python
dl = DataLoader(valid_ds, collate_fn=efficientdet.build_infer_batch)
```

And this can be extended even further, this is how **all** the dataloaders are actually defined behind the scenes:

```python
def train_dataloader(dataset, batch_tfms=None, **dataloader_kwargs) -> DataLoader:
    return transform_dataloader(
        dataset=dataset,
        build_batch=build_train_batch,
        batch_tfms=batch_tfms,
        **dataloader_kwargs
    )

def transform_dataloader(dataset, build_batch, batch_tfms=None, **dataloader_kwargs):
    collate_fn = partial(build_batch, batch_tfms=batch_tfms)
    return DataLoader(dataset=dataset, collate_fn=collate_fn, **dataloader_kwargs)
```

Pay attention to the fact that the **only** thing that changes between dataloaders is the `collate_fn`. `train_dataloader`, `valid_dataloader` and `infer_dataloader` are just synthetic sugar.

The only "not very obvious" thing is that we need to use `partial` to specify the `batch_tfms`. So, coming back to the first example, if you wanted to also specify batch transforms you would need to do:

```python
```python
dl = DataLoader(valid_ds, collate_fn=partial(efficientdet.build_infer_batch, batch_tfms=<Stuff>))
```

**Comment by lgvaz** [comment]
Alright, we are almost there,

First, create a dataset. You might be using your validation dataset, in which case you have a dataset already. Or else you have a list of images in memory (numpy arrays), in which case you can use `Dataset.from_images`.

Next, you need to decide if you want to predict everything at once, or in batches

### All at once
Just pass your dataset to `build_infer_batch`:

```python
batch, samples = efficientdet.build_infer_batch(my_dataset)
preds = efficientdet.predict(model, batch)
```

If you want to show the predictions:
```python
imgs = [sample["img"] for sample in samples]
show_preds(
    imgs=imgs,
    preds=preds,
    class_map=class_map,
    denormalize_fn=denormalize_imagenet,
    show=True,
)
```

Note that `samples` is returned by `build_infer_batch`, these means that all transforms are already applied to these samples. Eliminating the "challenging" problem described above.

Another advantage is that `samples` **may** also contain the targets, so we can implement another function in the future that shows the predictions and the targets together.

### Predict in batches
Create a dataloader:
```python
infer_dl = efficientdet.infer_dataloader(my_dataset, batch_size=6)

all_imgs, all_preds = [], []
for batch, samples in pbar(infer_dl):
    preds = efficientdet.predict(model=model, batch=batch)
    imgs = [sample["img"] for sample in samples]

    all_imgs.extend(imgs)
    all_preds.extend(preds)
```

While the code above is fairly simple, it's also very verbose, so we introduce a function to handle this case:
```python
samples, preds = efficientdet.predict_dl(dl=infer_dl)
```

The `show_preds` method can be used as before

---
**Note:** I tried to introduce another parameter in `show_preds` called `sample` so we could avoid this line:

```python
imgs = [sample["img"] for sample in samples]
```

But this would introduce more overhead to the user than advantages. It would mean that the user could pass `imgs` **or** `samples`, but not both. I think the drawback of having a single additional line is not that bad.
