### ISSUE TITLE
Generating Mantis Documentation using MkDocs

### ISSUE THREAD

**Issue by ai-fast-track** [lgvaz/mantisshrimp#197]
## 🚀 Feature
The goal is to automatically generates Matisshrimp Documentation using [MkDocs](https://www.mkdocs.org/). The latter uses Material Design, and produce high quality documentation. Using either existing or customized themes allows to create a documentation site that can easily be a visual identifier of the Mantisshrimp Framework.

**Comment by oke-aditya** [comment]
I will try this with mantis. Looks easy and good.

**Comment by oke-aditya** [comment]
Okay Apparently Mkdocs does not support .rst files.

https://github.com/mkdocs/mkdocs/issues/1817

Let's decide if we need our docs in .md or .rst. I would prefer .rst with Sphinx, we need to edit it and go to PyTorch theme or HuggingFace theme which would look nice.

This might help us in deciding stuff
https://github.com/JuliaFEM/JuliaFEM.jl/issues/49

Your thoughts @ai-fast-track and @lgvaz and @paras-jain

**Comment by paras-jain** [comment]
I think we should stick with .`rst`, reason being most of are docs are already `.rst` and that way we can stick with PyTorch or huggingface theme as @oke-aditya mentioned. Although `.md` is easy on the eyes and easy for some users, I don't see much of a trade-off here.

**Comment by oke-aditya** [comment]
Can be closed. As #206 #207 are merged too.
