### ISSUE TITLE
Slack invitation

### ISSUE THREAD

**Issue by bluesky314** [lgvaz/mantisshrimp#210]
Am unable to join the slack group without an invitation. Can you provide me one?

**Comment by oke-aditya** [comment]
Hey there @bluesky314 . Can you try joining our discord server. https://discord.gg/XGym3h

**Comment by oke-aditya** [comment]
cc @ai-fast-track @lgvaz

**Comment by lgvaz** [comment]
@bluesky314 We're still figuring out what plataform to use for building a community

Give us some days and we'll return to you with an answer in this thread, cool?

**Comment by lgvaz** [comment]
@bluesky314 , we decided to try [spectrum chat](https://spectrum.chat/mantis), it has a forum like structure

At this moment we're still experimenting with our options, so we will wait some more time before adding it to the readme, but you can already join! =)
