### ISSUE TITLE
Colab links are broken

### ISSUE THREAD

**Issue by ai-fast-track** [lgvaz/mantisshrimp#213]
## 🐛 Bug
When we click on the Colab badges in Docs, the links are broken.

**Example**: https://colab.research.google.com/github/lgvaz/mantisshrimp/blob/master/tutorials/01-getting_started.ipynb

**Source of the problem**: The `tutorials` folder has been deleted during the clean-up

**Solution**: Add a new folder called `notebooks` that we will be used as a canonical resource for both showcasing the notebooks from the GitHub repo, and for auto-generating the  `.md` files of the Docs.

We will try find find a mechanism to filter out the notebooks that shouldn't appear in the Docs.

**Comment by oke-aditya** [comment]
We can close this.

**Comment by ai-fast-track** [comment]
Fixed in this PR: https://github.com/lgvaz/mantisshrimp/pull/215
