### ISSUE TITLE
Improper Packaging with fastai requirement

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#222]
Re opened from #214 

@rashmimarganiatgithub
cc @lgvaz 

Let's solve this here. So that other people too can benefit if they face this.

We are trying to package our code properly for deployment still. #217.

@lgvaz  This improper packaging is a concern. #181 problem.

Really sorry @rashmimarganiatgithub this package is still preparing for its first release 0.1 and we yet need to fix such issues.

**Comment by oke-aditya** [comment]
That means in Kaggle competitions dataset. Upload fastai v2, PyTorch lightning wheels, install them then try to install mantisshrimp.

**Comment by rashmimarganiatgithub** [comment]
@oke-aditya I saw your previous comments here: "That means in Kaggle competitions dataset. Upload fastai v2, PyTorch lightning wheels, install them then try to install mantisshrimp."
 Hope I have installed it properly. here `nstalled
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sys
!pip install ../input/pycocotools/pycocotools-2.0-cp37-cp37m-linux_x86_64.whl
!pip install ../input/fastai2/fastai2-0.0.17-py3-none-any.whl
!pip install ../input/dogs-vs-cats-efficientnet-requirements/pytorch_lightning-0.8.5-py3-none-any.whl
! pip install ../input/withwhl/mantisshrimp-0.0.8-py3-none-any.whl`

**Comment by rashmimarganiatgithub** [comment]
> Re opened from #214
> 
> @rashmimarganiatgithub
> cc @lgvaz
> 
> Let's solve this here. So that other people too can benefit if they face this.
> 
> We are trying to package our code properly for deployment still. #217.
> 
> @lgvaz This improper packaging is a concern. #181 problem.
> 
> Really sorry @rashmimarganiatgithub this package is still preparing for its first release 0.1 and we yet need to fix such issues.

Can it be fixed within 1 or 2 days from now?. Only 9 days are remaining.

**Comment by oke-aditya** [comment]
We can fix it ASAP, can you share your kernel !!. @lgvaz and I can fix it up and handback kernel to you.

**Comment by lgvaz** [comment]
@rashmimarganiatgithub As I said in #214 , we do need a reproducer for the error, or else it's going to be very hard for us to fix the issue

**Comment by rashmimarganiatgithub** [comment]
> We can fix it ASAP, can you share your kernel !!. @lgvaz and I can fix it up and hand back kernel to you.

In order share the kernel you should be part of the team. Hence it is against the rules to share with other, so I have downloaded the code and shared you in google colab and will share the Kaggle dataset which I am using as the reference to fix it.

**Comment by rashmimarganiatgithub** [comment]
@oke-aditya  I have updated the comment with datasets. Hope it helps you to reproduce the bug easily.

**Comment by oke-aditya** [comment]
@lgvaz we need to have a look.

**Comment by rashmimarganiatgithub** [comment]
@oke-aditya any improvement on this?

**Comment by oke-aditya** [comment]
@rashmimarganiatgithub 
Yes, I am trying to create a proper wheel and packaging with #226 also #225 was made to fix it.
I have uploaded the wheel file of mantisshrimp on kaggle dataset for now. I will look into the installation as you have put. We will share a kernel/notebook that shows you how to install this package with internet off and wheels. 
I understand that competition is close to end maybe a week left. But we are trying best to get there !!

**Comment by lgvaz** [comment]
@rashmimarganiatgithub 

I updated the dependencies so you don't need to install pytorch-lightning

If I understood your problem correctly, you only need to do predictions offline, if that's the case, you don't need to install fastai, just fastcore will suffice.

In your notebooks you were doing:

```python
from mantisshrimp.models.rcnn.faster_rcnn import *
from mantisshrimp.models.rcnn import *
```
That can cause problems with our soft-dependencies, the correct way of importing is:

```python
from mantisshrimp.models.rcnn import faster_rcnn
```

[Here](https://colab.research.google.com/drive/1ZO8s8MtZwycrIiMbps7-AzYDYwEl4brB?usp=sharing) is a minimal installation notebooks, I hosted the wheel used there [here](https://drive.google.com/file/d/1OGKDSj3SQi_c1b793iMsNSPvhxkLu24K/view?usp=sharing)

Please tell us if everything is working now =)

**Comment by rashmimarganiatgithub** [comment]
> @rashmimarganiatgithub
> 
> I updated the dependencies so you don't need to install pytorch-lightning
> 
> If I understood your problem correctly, you only need to do predictions offline, if that's the case, you don't need to install fastai, just fastcore will suffice.
> 
> In your notebooks you were doing:
> 
> ```python
> from mantisshrimp.models.rcnn.faster_rcnn import *
> from mantisshrimp.models.rcnn import *
> ```
> 
> That can cause problems with our soft-dependencies, the correct way of importing is:
> 
> ```python
> from mantisshrimp.models.rcnn import faster_rcnn
> ```
> 
> [Here](https://colab.research.google.com/drive/1ZO8s8MtZwycrIiMbps7-AzYDYwEl4brB?usp=sharing) is a minimal installation notebooks, I hosted the wheel used there [here](https://drive.google.com/file/d/1OGKDSj3SQi_c1b793iMsNSPvhxkLu24K/view?usp=sharing)
> 
> Please tell us if everything is working now =)

@lgvaz @oke-aditya it is working... thanks much..
