### ISSUE TITLE
Cleaning up the INSTALL.md

### ISSUE THREAD

**Issue by ai-fast-track** [lgvaz/mantisshrimp#232]
## Cleaning up the **INSTALL.md**, and add it to **README**

INSTALL.md file has to be cleaned up. Here are some issues:

- In **Option A**: We have to highlight the different alternatives
- In **Option B**: some information is missing: After activating the conda environment, the user has to follow on of the alternatives listed in the Option A.

**Comment by oke-aditya** [comment]
We need to revamp the installation guidelines as well as the readme.
Suggestions for Readme.

1. Remove the Problem we are solving.
2. We don't need 2 photos. Yeah, we need to pay respect to the animal but can we make it only the animal photo?
3. We need to show the installation steps. Also, support for windows is experimental.
4. Make the code block from [Carbon](https://carbon.now.sh). It will look good. The first impression is the last impression. for most Github repos.
5. Remove the slack discussion channel for now. We need to think about it. We don't want to keep people at door waiting.

**Comment by JCustin** [comment]
Hey,

I can help rewrite your installation steps to give some more detail and clarity. I can also work on the Readme as Oke suggested, as well. I am on Windows so I can assist in explaining the installation on another Windows platform better, but I should be able to explain Linux, as well.

You mention that there's a step in Option B missing which is from Option A, which step is this necessarily?

**Comment by ai-fast-track** [comment]
Resolved in the [PR #235](https://github.com/lgvaz/mantisshrimp/pull/235)
