### ISSUE TITLE
AttributeError: module 'albumentations' has no attribute 'BboxParams'

### ISSUE THREAD

**Issue by FraPochetti** [lgvaz/mantisshrimp#234]
Hi folks,
I am literally just executing the [advanced guide](https://lgvaz.github.io/mantisshrimp/advanced_guide/) in Colab (GPU) line by line.
When I execute `train_tfm = AlbuTransform([A.Flip()])` I get:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-19-2627af07b24b> in <module>()
----> 1 train_tfm = AlbuTransform([A.Flip()])

/usr/local/lib/python3.6/dist-packages/mantisshrimp/transforms/albu_transform.py in __init__(self, tfms)
     10         import albumentations as A
     11 
---> 12         self.bbox_params = A.BboxParams(format="pascal_voc", label_fields=["labels"])
     13         super().__init__(tfms=A.Compose(tfms, bbox_params=self.bbox_params))
     14 

AttributeError: module 'albumentations' has no attribute 'BboxParams'
```
More than happy to dig further if you guys have any guidelines!

**Comment by oke-aditya** [comment]
Hey @FraPochetti I will have a look into this. I will try executing this script and let you know where exactly there is bug. You can have a look at our contributing.md [here](https://github.com/lgvaz/mantisshrimp/blob/master/CONTRIBUTING.md)

Also, you are a senior person in field of DL / ML. Do let us know about your thoughts on this package.

**Comment by oke-aditya** [comment]
I found the problem. The problem is Colab uses an old version of albumentations by default in their VMs. This causes an issue.
This feature was not there in old version of albumentations I guess.
Just run 
``` ! pip install --upgrade albumentations``` before and it would run fine.

After upgrading albumentations the code ran fine. I will update this in docs as well. Nice catch @FraPochetti

**Comment by lgvaz** [comment]
I faced this problem before as well!! Maybe we should add this to the docs, we can have a "common errors" section or something like that...
@ai-fast-track what do you think?

**Comment by ai-fast-track** [comment]
Maybe we can add a version specifier (minimum version) for the `albumentations` package. We also need to update the Advanced Guide to add `!pip install --upgrade albumentations`.

We can think about the "common errors" section or another alternative in Docs.

**Comment by lgvaz** [comment]
> Maybe we can add a version specifier (minimum version) for the albumentations package

This is definitely the correct thing to do, @oke-aditya can we specify versions on `settings.ini`?

**Comment by oke-aditya** [comment]
We should be able to. I will check it.

**Comment by FraPochetti** [comment]
Thanks for looking into this @oke-aditya !
It seems to work now. 

> Also, you are a senior person in the field of DL / ML. Do let us know about your thoughts on this package.
You are over-estimating me man! I will definitely let you guys know. I am gonna take the library for a spin starting tomorrow.

**Comment by valentinag4** [comment]
To be honest i was trying your solutions and was Impossible, you can follow this article by Albumentations official site, it works really good [https://albumentations.ai/docs/getting_started/installation/](url)
