### ISSUE TITLE
Issue Labelling and Stale marking

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#252]
## 🚀 Feature

We can instantiate Issue labeller bot. Which will automatically label issues accordingly.

It is available in GitHub Marketplace [here](https://github.com/marketplace/issue-label-bot).

Also we can mark old issues as stale using the stale bot [here](https://github.com/marketplace/stale).
After that It can be easily done by creating a stale.yml file in workflows.

**Comment by lgvaz** [comment]
I believe the first case is better handled with issue templates, which we already have in place

As for the second, maybe it's a bit early to have that. For example, #4 is an old issue, but it's not stale

**Comment by oke-aditya** [comment]
For first. Maybe we have few labels now. If they grow we can look for this as alternative.
True it's bit too early for second. Maybe when we get like 100+ issues a day we can do this. 

Lets close this and re open if needed.
