### ISSUE TITLE
Restructuring Model folder

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#61]
Following discussion on Slack and on issue #60 
We come to a structure as follows

so we can have a structure something like this
-> backbones (use torchvision + custom)
-> layers (for some layers that you would use in the backbone)
-> models
-----> model_name_folder (e.g. fasterrcnn)
----------> model.py (take help of backbones here)
----------> dataloader.py (with minor edits for every mode)

model.py includes train_step, validation_step, test_step.

And train.py (code for training and inference from the model) Would be in the examples folder.

Inheriting from rcnn to faster rcnn is extra inter code coupling which we might avoid.
Let's have seperate structures for rcnn, fast rcnn and faster rcnn. It would make debugging easier as well.

Also, I will raise a PR for contributing.MD and FAQs.MD (will check how to make .rst)

**Comment by lgvaz** [comment]
Could you explain what do you have in mind to be inside `dataloader.py`? Currently a dataloader is something as short as:
```python
    def dataloader(cls, dataset, **kwargs) -> DataLoader:
        def collate_fn(data):
            ts = [cls.build_training_sample(**o) for o in data]
            return list(zip(*ts))

        return DataLoader(dataset=dataset, collate_fn=collate_fn, **kwargs)
```

I think it makes much more sense to have this as an method of the class than unnecessary splitting in another file

**Comment by lgvaz** [comment]
Also, as we discussed in slack, I still think `FasterRCNN` and `MaskRCNN` should inherit from a common parent class that implements `training_step` and `validation_step`, these methods are exactly the same for both models.

If you take a look on how torchvision implemented it, they have `MaskRCNN` that inherits from `FasterRCNN` that inherits from `GeneralizedRCNN`, I think we should draw inspiration from this.

I'm not saying to follow the exact same structure, I'm just saying we need a common `RCNN` parent

**Comment by oke-aditya** [comment]
Dataloader can be method of the file, I think no need of different of file. 

But the inheriting from RCNN is something possible only in RCNN style models, would it be possible for SSD, YOLO etc ? It would lead to an inconsistent API.

This multiple inheritance makes it a bit hard to customize I felt.

**Comment by lgvaz** [comment]
> But the inheriting from RCNN is something possible only in RCNN style models

That's exactly right! I believe this actually makes the code very clear instead of confusing, it wouldn't make sense to do `YOLO(RCNNModule)`, YOLO is not an RCNN extension!! hahaha

For making it even clearer, maybe we can have the folder structure like so
```
-> model
----> model_family (rcnn)
--------> rcnn.py
--------> mask_rcnn.py
--------> faster_rcnn.py
```

Which is what I tried to do, but didn't had time to do it properly so it became a mess 😅

**Comment by oke-aditya** [comment]
Yeah this sounds better. It would mean we could have YOLO_family with v1, v2, v3, v4 (now) etc.

Also last poin what is mantis_module.py file ? It's inheriting class with some imports. 

Do we really need it?

**Comment by lgvaz** [comment]
> It would mean we could have YOLO_family with v1, v2, v3, v4 (now) etc.

That's it! Although we should call the folder simply YOLO

> Do we really need it?

What it's currently doing is injecting some dependencies like `ParameterSplitsMixin`, which helps in fine-tuning.

I'm working to integrate that directly in lightning thought, once it gets implemented there we can remove it from here

**Comment by lgvaz** [comment]
It also serves for defining a common interface for all our models. Currently we only have `dataloader` there, but I see other things in the future like `predict`

**Comment by oke-aditya** [comment]
``` predict ``` may be model specific so as of now let it be there. You might remove it as you said once it is in lightning directly.

**Comment by lgvaz** [comment]
> predict may be model specific so as of now let it be there.

For sure it's model specific, but the interface should be common in the base class. So in `MantisModule` we just define it as an `@abstractmethod`, makes sense?

**Comment by oke-aditya** [comment]
Yes complete sense. So it's sorted now 👍 Closing for now.

**Comment by lgvaz** [comment]
Actually, we should leave it open, we close it once with make a PR implement those changes 😁

**Comment by oke-aditya** [comment]
Adding backbones with #64
