### ISSUE TITLE
Freeze weights when fine-tuning hub.detr

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#72]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
Freeze model weights when fine-tuning with `hub.detr`

**Describe the solution you'd like**
Pass a flag to `run_detr` to freeze the appropriate weights.

**Comment by oke-aditya** [comment]
Defunct issue. Detr is gonna be revamped and not stay in Hub.

**Comment by lgvaz** [comment]
We probably need to remove detr off the repo as it's right, idk

**Comment by oke-aditya** [comment]
We can keep it as of now. We need a revamp of it. Like I am trying in my repo https://github.com/oke-aditya/pytorch_detr

But still there are some concerns while integrating.
