### ISSUE TITLE
Refactors MantisMaskRCNN

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#82]
## 🚀 Feature
Implement for MantisMaskRCNN what we did with MantisFasterRCNN, that's it =)

**Comment by lgvaz** [comment]
@oke-aditya interested in this? 😄

**Comment by oke-aditya** [comment]
Yep, will need to check this. I will try it, would need some help. I guess Mask RCNN is very similar.

**Comment by lgvaz** [comment]
It's very similar, and I'll help you 😄

**Comment by oke-aditya** [comment]
I guess this issue is done. It should have been closed automatically though.

**Comment by lgvaz** [comment]
Fixed in pr #86
