### ISSUE TITLE
Penn-Fudan dataset example

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#85]
## 📓 New <Tutorial/Example>
**Is this a request for a tutorial or for an example?**  
Example

**What is the task?**
image segmentation

**Is this example for a specific model?**
MaskRCNN and Detr, maybe show can we experiment with both in the same notebook?

**Is this example for a specific dataset?**
[PennFundan](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) used in the torchvision tutorial. Simple dataset easy to get good results. Dataset format is a little bit complicated though.

---
**Don't remove**
Main issue for examples: #39

**Comment by oke-aditya** [comment]
- It will be good if we add Mask RCNN example also.

**Comment by lgvaz** [comment]
Yes! A MaskRCNN example is also described in the OP
