### ISSUE TITLE
Documentation colab badge does not render

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#94]
## 🐛 Bug
**Describe the bug**
Colab badge does not render properly on documentation. But it does locally.

**To Reproduce**
Take a look [here](https://lgvaz.github.io/mantisshrimp/tutorials/hub_detr_finetune_pennfundan.html)

**Expected behavior**
Show the colab badge

**Screenshots**
![Screenshot 2020-06-18 at 3 03 46 PM](https://user-images.githubusercontent.com/16520544/85056036-eb496580-b174-11ea-89f8-6e57f731b5fd.png)

**Comment by oke-aditya** [comment]
Have a look [here](https://github.com/weiji14/deepbedmap/issues/61)

**Comment by oke-aditya** [comment]
As well as [here](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb#scrollTo=8QAWNjizy_3O)

**Comment by lgvaz** [comment]
The badge works correctly when inside a notebook, the problem is when it gets converted to an html page (via sphinx).

For some reason only the badges show but the link isn't there

**Comment by oke-aditya** [comment]
Closed with the new documention #197 Closes this.
