### ISSUE TITLE
Add Docker support with GPU

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#97]
## 🚀 Feature
 
Add support for containerizing mantisshrimp.
We should create a Dockerfile, and a .dockerignore file

**Comment by lgvaz** [comment]
That's a great idea, and it should make it very easy to install the lib, this would even solve the problem of pycocotools in windows right?

**Comment by oke-aditya** [comment]
Yes, it will solve Pycocotools problem. Can you add CI for docker build on Github. So that we can check if container builds with our dockerfile.

**Comment by lgvaz** [comment]
Can you make a PR for that?😄

**Comment by oke-aditya** [comment]
I will make PR for the docker build yaml file. But you need to add the secrets.
Check [here](https://medium.com/better-programming/github-actions-for-docker-eaf22bbcc879)

**Comment by oke-aditya** [comment]
Not yet solved with #104 . Will add a direct GPU supported NVIDIA container runtime docker itself. 

It will solve all the problems and will not create a multiple dockerfile issue.

**Comment by ai-fast-track** [comment]
@oke-aditya, @lgvaz , Paperspace provides GPU-enabled container that are pre-loaded with both fastai2 library and the latest fastai course (V4). Check out the references here below, they might be adapted to mantisshrimp. 

https://github.com/Paperspace/fastai-docker/tree/master/fastai-v4
https://github.com/Paperspace/fastai-docker/blob/master/fastai-v4/Dockerfile
https://github.com/NVIDIA/nvidia-docker

**Comment by oke-aditya** [comment]
Yes gonna adapt them 👍 We will have a docker file very similar to them.
