### ISSUE TITLE
Pycoco tools do not install / run on Windows

### ISSUE THREAD

**Issue by oke-aditya** [lgvaz/mantisshrimp#98]
## 🐛 Bug
**Describe the bug**

Simple this isn't our side issue though but if people come here they should know about this.

**Comment by oke-aditya** [comment]
Pycoco tools do not run on windows. We are looking to use other metrics.
[Issue with Pycoco tools](https://github.com/cocodataset/cocoapi/issues/9#issuecomment-217339740)

For now issue can be solved with docker container #97.
Or use [this ](https://github.com/philferriere/cocoapi)

**Comment by oke-aditya** [comment]
- For now, Windows users can use this as a solution. We have tested this. But do not officially support or nor maintain the repo to support this. It is just a workaround which has worked well.

You can find additional details in README of [this](https://github.com/philferriere/cocoapi) coco api repo.
- In short

1. Install any dependency if missing like cython, etc.
2.  Install Visual C++ 14/2015 build tools
3.  `pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI`

**Comment by oke-aditya** [comment]
Another solution is to use Docker with Linux backend containers and run mantisshrimp docker image in it.

**Comment by ai-fast-track** [comment]
In Windows, Docker does not support GPU for now (GPU support will be in WSL2)

**Comment by oke-aditya** [comment]
- WSL2 is already launched with Windows 10 May 2020 update. I am using WSL 2 as docker linux backend.

**Comment by ai-fast-track** [comment]
It wasn't publicly released: You have to enroll in their beta testing group. The installation seems to be quiet a challenge based on this fastai thread: [Platform: Windows 10 using WSL2 w/GPU](https://forums.fast.ai/t/platform-windows-10-using-wsl2-w-gpu/73521)

**Comment by oke-aditya** [comment]
It is quite simple. The above can be a good reference to how to configure this.
1. Have Windows 10 May 2020 Update (minimum)
2. Have your NVIDIA GPU with proper CUDA installed. This the user can refer to [NVIDA](https://developer.nvidia.com/cuda/wsl) 
3. Install WSL2. Info [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
4. Setup WSL2. Again a brief commands. Given in the above page.
5. Install Ubuntu from Windows store. Should be a few clicks.
6. Install Docker it will give you option of using WSL2 backend. Or refer Docker docs to set it up. Fairly simple.
7. Since we provide container that is based on NVIDIA Ubuntu they can directly run mantisshrimp. It will use CUDA.

I have set up this stuff and able to use WSL2. Without any beta testing etc. If you have May Update it comes prepacked. You need to enable it and switch from WSL1 -> WSL2.

**Comment by lgvaz** [comment]
Alternatives are already in place in docs, closing this

**Comment by roboserg** [comment]
> Alternatives are already in place in docs, closing this

Do you have a link in the docs for Windows install? There seems to be nothing about Windows or Docker - https://airctic.com/0.7.0/install/
