### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by lgvaz** [lgvaz/mantisshrimp#99]
## 🚀 Feature
Deployment, the thing we as ML devs always keep pushing forward can't be pushed forward no more.

Let's first discuss ideas and work on minimal examples before jumping head first on this one. I myself don't really know how deployment works, so I'll be starting with very simple apps and I will be sharing my journey here.

This is going to be a hard one, let's not do this alone, collective brain power is what we need right now, so I'll tag everyone 😅

@oke-aditya @paras-jain @ai-fast-track

**Comment by lgvaz** [comment]
As we previously discussed, it's a good a idea to start with streamlit, so I'll do that

**Comment by oke-aditya** [comment]
- Add docker support.
- Publish to PyPi experimental branch.
- Add support for Amazon Container Registry and Google Container Registry.
- Try with Kubernetes as well.
- Run with KubeFlow and AirFlow.

**Comment by ai-fast-track** [comment]
Start small and build up on that. The way I see it:
1- Use streamlit
2- Deploy locally with a toy example (MantisFasterRCNN + Toy Dataset)
3- Use docker locally
4- Deploy docker container on the cloud:
5- Rinse and repeat

**Comment by oke-aditya** [comment]
#97 should be the first big step.
